FROM node:22-alpine

WORKDIR /app

COPY package.json .
COPY .dockerignore .
RUN yarn install --frozen-lockfile

COPY . .
# RUN cp .env.prod .env
RUN yarn build

RUN yarn cache clean
RUN rm -rf ./src

CMD ["yarn", "start"]
