version: '3.8'

name: app-resource-prod

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - '4000:4000'
    networks:
      - prod-network

  client:
    container_name: client
    depends_on:
      - server
    build:
      context: client
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - '3000:3000'
    networks:
      - prod-network

networks:
  prod-network:
