import type { Metadata } from 'next'

import { FC, ReactNode } from 'react'

import { RestApiProvider } from '@/core/rest-api'
import { UiProvider } from '@/core/ui'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// interface
interface IRootLayoutProps {
  children: ReactNode
}

// component
const RootLayout: FC<Readonly<IRootLayoutProps>> = (props) => {
  const { children } = props

  // return
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <UiProvider>
          <RestApiProvider>{children}</RestApiProvider>
        </UiProvider>
      </body>
    </html>
  )
}

export default RootLayout
